### ISSUE TITLE
[Weblate] German translation completed on Weblate

### ISSUE THREAD

**Issue by inxomnyaa** [aseprite/languages#30]
I've fully translated the german language on Weblate. The linked repo https://github.com/dotheflopboy/Aseprite-German-Translation in the Readme simply contained too many mistakes, as it likely was auto-translated.
You might want to update the Readme to use the Weblate version.

**Comment by dacap** [comment]
Hi @inxomnyaa, thanks a lot for your contributions! We'll try to include the most complete translations in the next release of Aseprite (including yours).

About linking to the Weblate translation instead of the extension one, actually the Weblate format is a little different and will be supported only since the next v1.3.3 (mainly for strings with new lines "\n" strings). So this new format is not compatible with v1.3.2.

**Comment by inxomnyaa** [comment]
> the Weblate format is a little different

Just figured that out, no problem!

**Comment by inxomnyaa** [comment]
I have created an updated fork, including some scripts to convert the Weblate files into valid translation files supported in v1.3.2
https://github.com/inxomnyaa/Aseprite-German-Translation

**Comment by dacap** [comment]
Thanks for your help with the German translation @inxomnyaa. I'll close this issue now :v:
